import { DashboardPage, DashboardPageAdapter } from "dashboard_page.slint";
import { BalancePage, BalancePageAdapter } from "balance_page.slint";
import { ListViewPage } from "list_view_page.slint";
import { DeviceListPage, DeviceListPageAdapter} from "device_list_page.slint";
import { TestListPage, TestListPageAdapter } from "test_list_page.slint";
import { TextEditPage } from "text_edit_page.slint";

export { BalancePage, BalancePageAdapter, DashboardPage, DashboardPageAdapter, ListViewPage, TextEditPage, DeviceListPage, DeviceListPageAdapter, TestListPage, TestListPageAdapter }