import { PageScrollView } from "../components/page-scroll-view.slint";
import { PageContainer } from "../components/page-container.slint";
import { ManualBrewScreen } from "manual-brew.slint";
import { Images } from "../images.slint";
import { Theme } from "../theme.slint";
import { Header } from "../components/header.slint";
import { GlobalSettings } from "../global_settings.slint";
import { Menu, MenuPage } from "../components/menu.slint";


export component Selection {
    height: 480px;
    width: 800px;

    VerticalLayout {
        padding-bottom: 50px;

        Header { }

        i-page-scroll-view := PageScrollView {
            vertical-stretch: 1;
            page-count: 3;

            PageContainer {
                clicked => {
                    i-page-scroll-view.toggle-selection(self.index, self.x);
                }

                index: 0;
                selected <=> i-page-scroll-view.selection;
                selected-width: i-page-scroll-view.selected-width;
                selected-height: i-page-scroll-view.selected-height;
                selected-h-offset: i-page-scroll-view.selected-h-offset;

                VerticalLayout {
                    alignment: center;
                    spacing: 20px;
                    Image {
                        source: Images.latte;
                        height: 150px;
                    }

                    Text {
                        text: "Latte Macchiato";
                        horizontal-alignment: center;
                        font-size: 30px;
                    }
                }

            }

            PageContainer {
                clicked => {
                    i-page-scroll-view.toggle-selection(self.index, self.x);
                }

                index: 1;
                selected <=> i-page-scroll-view.selection;
                selected-width: i-page-scroll-view.selected-width;
                selected-height: i-page-scroll-view.selected-height;
                selected-h-offset: i-page-scroll-view.selected-h-offset;

                VerticalLayout {
                    alignment: center;
                    spacing: 20px;
                    Image {
                        source: Images.cappuccino;
                        height: 150px;
                    }

                    Text {
                        text: "Cappuccino";
                        horizontal-alignment: center;
                        font-size: 30px;
                    }
                }
            }


            PageContainer {
                clicked => {
                    i-page-scroll-view.toggle-selection(self.index, self.x);
                }

                index: 2;
                selected <=> i-page-scroll-view.selection;
                selected-width: i-page-scroll-view.selected-width;
                selected-height: i-page-scroll-view.selected-height;
                selected-h-offset: i-page-scroll-view.selected-h-offset;

                VerticalLayout {
                    alignment: center;
                    spacing: 20px;
                    Image {
                        source: Images.americano;
                        height: 150px;
                    }

                    Text {
                        text: "Americano";
                        horizontal-alignment: center;
                        font-size: 30px;
                    }
                }
            }

            PageContainer {
                clicked => {
                    i-page-scroll-view.toggle-selection(self.index, self.x);
                }

                index: 3;
                selected <=> i-page-scroll-view.selection;
                selected-width: i-page-scroll-view.selected-width;
                selected-height: i-page-scroll-view.selected-height;
                selected-h-offset: i-page-scroll-view.selected-h-offset;

                VerticalLayout {
                    alignment: center;
                    spacing: 20px;
                    Image {
                        source: Images.espresso;
                        height: 150px;
                    }

                    Text {
                        text: "Espresso";
                        horizontal-alignment: center;
                        font-size: 30px;
                    }
                }
            }


            PageContainer {
                clicked => {
                    //i-page-scroll-view.toggle-selection(self.index, self.x);
                    GlobalSettings.current-page = 1;
                }

                index: 4;
                selected <=> i-page-scroll-view.selection;
                selected-width: i-page-scroll-view.selected-width;
                selected-height: i-page-scroll-view.selected-height;
                selected-h-offset: i-page-scroll-view.selected-h-offset;

                VerticalLayout {
                    alignment: center;
                    spacing: 20px;
                    Image {
                        source: Images.settings;
                        colorize: #c97767ff;
                        height: 150px;
                    }

                    Text {
                        text: "Manual";
                        horizontal-alignment: center;
                        font-size: 30px;
                    }
                }
            }
        }
    }

    i-menu := Menu {
        stays-open: true;
        preferred-width: 100%;
        preferred-height: 100%;
        start-y: 35px;
        end-y: 75px;
        menu-width: root.width / 3;
        menu-height: root.height - 75px;

        opend => {
            i-menu-page.current-index = 0;
        }

        i-menu-page := MenuPage {
            close => {
                i-menu.hide();
            }

            preferred-width: 100%;
            preferred-height: 100%;
        }
    }
}
