import { HorizontalBox, VerticalBox, StandardTableView, GroupBox} from "std-widgets.slint";
import { GlobalSettings } from "../global_settings.slint";
import { Page } from "page.slint";

export global TestListPageAdapter {
    in property <[[StandardListViewItem]]> row_data: [
        [
            { text: "Full Board Test" },
            { text: "True" },
            { text: "00:02:33" },
            { text: "Board 1" },
        ],
        [
            { text: "Full Board Test" },
            { text: "True" },
            { text: "00:07:37" },
            { text: "Board 2" },
        ],
        [
            { text: "Full Board Test" },
            { text: "False" },
            { text: "00:22:33" },
            { text: "Board 3" },
        ],
        [
            { text: "Full Board Test" },
            { text: "True" },
            { text: "00:12:33" },
            { text: "Board 4" },
        ],
        [
            { text: "Full Board Test" },
            { text: "False" },
            { text: "00:04:53" },
            { text: "Board 5" },
        ],
        [
            { text: "Full Board Test" },
            { text: "True" },
            { text: "00:01:32" },
            { text: "Board 5" },
        ],
    ];

    callback sort_ascending(int);
    callback sort_descending(int);
}

export component TestListPage inherits Page {
    title: @tr("Tests");
    show-enable-switch: false;
    description: @tr("StandardTableView can be used to display a list of text elements in columns and rows. It can be imported from \"std-widgets.slint\"");

    HorizontalBox {
        vertical-stretch: 1;

        StandardTableView {
            sort-ascending(index) => {
                TestListPageAdapter.sort_ascending(index);
            }

            sort-descending(index) => {
                TestListPageAdapter.sort-descending(index);
            }

            columns: [
                { title: @tr("Test Name") },
                { title: @tr("Pass") },
                { title: @tr("Runtime") },
                { title: @tr("Device") },
            ];
            rows: TestListPageAdapter.row_data;
        }
    }
}
