// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Theme } from "../theme.slint";
import { MenuButton } from "menu-button.slint";


export component MenuBackground inherits Rectangle {
    border-radius: 4px;
    background: Theme.palette.ebony-radial-gradient;
    clip: true;
}


export component Menu {
    in-out property <bool> menu-button-visible;
    in property <length> start-y;
    in property <length> end-y;
    in property <bool> stays-open;
    in property <length> menu-width <=> i-menu-container.width;
    in property <length> menu-height <=> i-menu-container.height;
    out property <bool> open;

    callback opend();
    callback closed();

    public function hide-button() {
        menu-button-visible = false;
    }

    public function open-menu() {
        open = true;
    }

    public function hide() {
        menu-button-visible = false;
        open = false;
        closed();
    }

    private property <int> container-visibility;

    states [
        open when root.open : {
            container-visibility: 1.0;
            i-menu-container.y: end-y;

            in {
                animate i-menu-container.y { duration: Theme.durations.medium; }
            }
            out {
                animate container-visibility, i-menu-container.y { duration: Theme.durations.medium; }
            }
        }
    ]

    if (open) : Rectangle {
        background: Theme.palette.pure-black;
        opacity: 0.5;

        TouchArea {
            clicked => {
                hide();
            }
        }
    }

    i-menu-container := Rectangle {
        x: (parent.width - self.width) / 2;
        y: parent.height - start-y;
        width: root.width / 3;
        height: root.height - 75px;

        i-container := MenuBackground {
            visible: container-visibility == 1.0;

            // avoid click-through
            TouchArea {}

            @children
        }

        if(menu-button-visible || container-visibility == 1.0 || stays-open) : HorizontalLayout {
            y:  -i-menu-button.height / 2;
            alignment: center;

            VerticalLayout {
                alignment: start;

                i-menu-button := MenuButton {
                    clicked => {
                        if(open) {
                            hide();
                        } else {
                            open-menu();
                        }
                    }
                }
            }
        }
    }
}

import { MenuOverviewAdapter } from "menu-overview.slint";

export { MenuOverviewAdapter /* , SettingsAdapter */ }

export global MenuPageAdapter {
    in property <[StandardListViewItem]> model: [
        { text: "Production & Self-consumption"},
        { text: "Usage"},
        { text: "Balance"},
        { text: "Weather"},
    ];
    in-out property <int> selected-index;
}

export component MenuPage {
    in-out property <int> current-index;

    callback page-changed(/* index */ int);
    callback close;

    private property <bool> show-settings;

    function back() {
        current-index = 0;
    }

    Rectangle {
        x: -parent.width * current-index;
        width: 2 * parent.width;
        clip: true;

        animate x { duration: Theme.durations.fast; }

        /*
        if(current-index == 0) : Settings {
            close => {
                root.close();
            }

            width: root.width;
        }
        */
    }
 }


