export component NavButton {
    in property <string> text: "Button";
    in property <image> icon;

    in property <bool> icon-right: false;

    callback clicked <=> ta.clicked;

    min-height: 10px;
    min-width: 200px;

    accessible-role: button;
    accessible-label: root.text;

    ta := TouchArea {
        x: 0;
        y: 0;
        height: root.height;
        width: root.width;
    }

    background := Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 20px;
        drop-shadow-color: transparent;
        drop-shadow-offset-y: 1px;
        background: Colors.lightgray;
        opacity: 0.4;
    }

    layout := HorizontalLayout {
        padding-left: 24px;
        padding-right: 24px;
        spacing: 20px;

        if (!icon-right && root.icon.width > 0 && root.icon.height > 0): Image {
            source <=> root.icon;
            width: 50px;
            //opacity: root.text-opacity;
            //colorize: root.colorize-icon ? root.text-color : transparent;
        }

        if (root.text != ""): Text {
            text: root.text;
            //color: root.text-color;
            //opacity: root.text-opacity;
            vertical-alignment: center;
            horizontal-alignment: center;
            //font-weight: MaterialFontSettings.label-large.font-weight;
            accessible-role: none;
            font-size: 60px;

            animate color {
                duration: 250ms;
                easing: ease;
            }
        }

        if (icon-right && root.icon.width > 0 && root.icon.height > 0): Image {
            source <=> root.icon;
            width: 50px;
            //opacity: root.text-opacity;
            //colorize: root.colorize-icon ? root.text-color : transparent;
        }
    }
}
