[package]
name = "embedded-dal"
version = "0.0.0"
edition = "2021"
authors = [
    "Joel Schulz-Andres <joel@systemscape.de>",
    "Julian Dickert <julian@systemscape.de>",
]
description = "A display abstraction layer for embedded devices"
license = "MIT"
categories = ["no-std", "embedded", "visualization"]
readme = "README.md"

[features]
default = ["defmt", "event_process", "fmc", "stm32f469"]
defmt = ["dep:defmt"]
event_process = []
fmc = ["dep:stm32-fmc"]
stm32f469 = ["dep:embedded-alloc"]


[dependencies]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "2a38787a8375675a7c3b8d7d7dc4ca6505734bca", features = [
    "defmt",
    "stm32f469ni",
    "unstable-pac",
    "time-driver-any",
    "exti",
] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "2a38787a8375675a7c3b8d7d7dc4ca6505734bca", features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
    "generic-queue",
] }

embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "2a38787a8375675a7c3b8d7d7dc4ca6505734bca", features = [
    "task-arena-size-32768",
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
    #"integrated-timers",

] }

embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git", rev = "2a38787a8375675a7c3b8d7d7dc4ca6505734bca", features = [
    "defmt",
] }


embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "2a38787a8375675a7c3b8d7d7dc4ca6505734bca", features = [
    "defmt",
] }

embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "2a38787a8375675a7c3b8d7d7dc4ca6505734bca", features = [
    "defmt",
] }


embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"

static_cell = "2.1"

stm32-fmc = { version = "0.3", default-features = false, features = [
    "sdram",
], optional = true }


slint = { version = "1.6", default-features = false, features = [
    "compat-1-2",
    "renderer-software",
    "libm",
    "unsafe-single-threaded",
] }
embedded-alloc = { version = "0.5", optional = true }

defmt = { version = "0.3", optional = true }
defmt-rtt = "0.4"

panic-probe = { version = "0.3", features = ["print-defmt"] }

cortex-m = { version = "0.7.6", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.0"

num_enum = { version = "0.7", default-features = false }

#pas-co2-rs = { version = "0.1.0-beta.1", git = "ssh://git@github.com/Systemscape/pas-co2-rs.git", features = [    "defmt",] }
pas-co2-rs = { path = "../pas-co2-rs", features = ["defmt"] }


[build-dependencies]
slint-build = { version = "1.6" }

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
codegen-units = 1
debug = 2
incremental = false
lto = "fat"
opt-level = 's'
