[package]
name = "embedded-dal"
version = "0.0.0"
edition = "2021"
authors = [
    "Joel Schulz-Andres <joel@systemscape.de>",
    "Julian Dickert <julian@systemscape.de>",
]
description = "A display abstraction layer for embedded devices"
license = "MIT"
categories = ["no-std", "embedded", "visualization"]
readme = "README.md"

[features]
default = ["defmt", "event_process", "fmc", "stm32f469"]
defmt = ["dep:defmt"]
event_process = []
fmc = ["dep:stm32-fmc"]
stm32f469 = ["dep:embedded-alloc"]


[dependencies]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "daaaf50298144a245d026e70f4fa3c6eb856276a", features = [
    "defmt",
    "stm32f469ni",
    "unstable-pac",
    "time-driver-any",
    "exti",
    "chrono",
] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "daaaf50298144a245d026e70f4fa3c6eb856276a", features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
] }

embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "daaaf50298144a245d026e70f4fa3c6eb856276a", features = ["task-arena-size-32768", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }

embedded-hal = "1.0.0"

stm32-fmc = { version = "0.3", default-features = false, features = ["sdram"], optional = true }


slint = { version = "1.6", default-features = false, features = ["compat-1-2", "renderer-software", "libm", "unsafe-single-threaded"] }
embedded-alloc = { version = "0.5", optional = true }

defmt = {version = "0.3", optional = true }
defmt-rtt = "0.4"

panic-probe = { version = "0.3", features = ["print-defmt"] }

cortex-m = { version = "0.7.6", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.0"

num_enum = { version = "0.7", default-features = false }

[build-dependencies]
slint-build = "1.6"

[badges]
maintenance = { status = "actively-developed" }
