[package]
name = "embedded-dal"
version = "0.0.0"
edition = "2021"
authors = ["Joel Schulz-Andres <joel@systemscape.de>", "Julian Dickert <julian@systemscape.de>"]
description = "A display abstraction layer for embedded devices"
license = "MIT"
categories = ["no-std", "embedded", "visualization"]
readme = "README.md"

[dependencies]
embassy-stm32 = {git = "https://github.com/Systemscape/embassy.git", rev = "d5f8161fc0d842a1c84a2c7af3ca2a4b54e7a303", features = ["defmt", "stm32f469ni", "unstable-pac", "time-driver-any", "exti", "chrono"]}
embassy-time = {git = "https://github.com/Systemscape/embassy.git", rev = "d5f8161fc0d842a1c84a2c7af3ca2a4b54e7a303", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"]}


defmt = "0.3"
defmt-rtt = "0.4"

panic-probe = { version = "0.3", features = ["print-defmt"] }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"

[badges]
maintenance = { status = "actively-developed" }
