[package]
name = "embedded-dal"
version = "0.0.0"
edition = "2021"
authors = [
    "Joel Schulz-Andres <joel@systemscape.de>",
    "Julian Dickert <julian@systemscape.de>",
]
description = "A display abstraction layer for embedded devices"
license = "MIT"
categories = ["no-std", "embedded", "visualization"]
readme = "README.md"

[features]
default = ["defmt", "event_process"]
defmt = ["dep:defmt"]
event_process = []

[dependencies]
embassy-stm32 = { git = "https://github.com/Systemscape/embassy.git", rev = "5e5bc37db800fcf8234bcc2f846d486a890810ff", features = [
    "defmt",
    "stm32f469ni",
    "unstable-pac",
    "time-driver-any",
    "exti",
    "chrono",
] }
embassy-time = { git = "https://github.com/Systemscape/embassy.git", rev = "5e5bc37db800fcf8234bcc2f846d486a890810ff", features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
] }

embassy-executor = { git = "https://github.com/Systemscape/embassy.git", rev = "5e5bc37db800fcf8234bcc2f846d486a890810ff", features = ["task-arena-size-32768", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }

embedded-hal = "1.0.0"

defmt = {version = "0.3", optional = true }
defmt-rtt = "0.4"

panic-probe = { version = "0.3", features = ["print-defmt"] }

cortex-m = { version = "0.7.6", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.0"
num_enum = { version = "0.7", default-features = false }

[badges]
maintenance = { status = "actively-developed" }
