[package]
name = "embedded-dal"
version = "0.0.0"
edition = "2021"
authors = ["Joel Schulz-Andres <joel@systemscape.de>", "Julian Dicker <julian@systemscape.de>"]
description = "A display abstraction layer for embedded devices"
license = "MIT"
categories = ["no-std", "embedded", "visualization"]
readme = "README.md"

[dependencies]

[badges]
maintenance = { status = "actively-developed" }
