import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { BalancePage, BalancePageAdapter, DashboardPage, DashboardPageAdapter, DeviceListPage, DeviceListPageAdapter, TestListPage, TestListPageAdapter } from "pages/pages.slint";
import { GlobalSettings } from "global_settings.slint";
import { SideBar } from "side_bar.slint";

export { BalancePageAdapter, DashboardPageAdapter, DeviceListPageAdapter, TestListPageAdapter }

component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 480px;
    min-width: 800px;
    min-height: 480px;
    title: @tr("Dislodged");
    
    default-font-size: GlobalSettings.FontSizeDefault;

    HorizontalLayout {
        spacing: 5px;
        padding: 5px;
        height: 100%;

        side-bar := SideBar {
            logo: @image-url("icons/logo.svg");
            title: @tr("Dislodged CI");
            model: [
                { icon: @image-url("icons/gauge.svg"), name: @tr("Menu" => "Dashboard") },
                { icon: @image-url("icons/microchip.svg"), name: @tr("Menu" => "Devices") },
                { icon: @image-url("icons/pen-to-square.svg"), name: @tr("Menu" => "Tests") },
                { icon: @image-url("icons/calendar-days.svg"), name: @tr("Menu" => "Calendar") },
                { icon: @image-url("icons/folder-closed.svg"), name: @tr("Menu" => "Test Data") },
                { icon: @image-url("icons/arrow-right-long.svg"), name: @tr("Menu" => "Workflow") },
                { icon: @image-url("icons/chart-column.svg"), name: @tr("Menu" => "Results") },
                { icon: @image-url("icons/code.svg"), name: @tr("Menu" => "Endpoints") },
                { icon: @image-url("icons/credit-card.svg"), name: @tr("Menu" => "Balance") },
                { icon: @image-url("icons/gear.svg"), name: @tr("Menu" => "Settings") },
            ];
        }

        // Vertical separator line between SideBar and Page
        Rectangle {
            border-width: 1px;
            border-color: black;
            height: 100%;
            width: 1px;
        }

        if(GlobalSettings.current-page == 0): DashboardPage { }
        if(GlobalSettings.current-page == 1): DeviceListPage { }
        if(GlobalSettings.current-page == 2): TestListPage { }
        if(GlobalSettings.current-page == 3): DashboardPage { }
        if(GlobalSettings.current-page == 4): DashboardPage { }
        if(GlobalSettings.current-page == 5): DashboardPage { }
        if(GlobalSettings.current-page == 6): DashboardPage { }
        if(GlobalSettings.current-page == 7): DashboardPage { }
        if(GlobalSettings.current-page == 8): DashboardPage { }
        if(GlobalSettings.current-page == 9): DashboardPage { }
    }
}
