

// Default button widget with Material Design Filled Button look and feel.
export component NavButton {
    in property <string> text: "Button";
    in property <image> icon;

    in property <bool> icon-right: false;

    callback clicked <=> ta.clicked;

    min-height: 10px;
    min-width: 200px;

    accessible-role: button;
    accessible-label: root.text;

    ta := TouchArea {
        x: 0;
        y: 0;
        height: root.height;
        width: root.width;
    }

    background := Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 20px;
        drop-shadow-color: transparent;
        drop-shadow-offset-y: 1px;
        background: Colors.lightgray;
        opacity: 0.4;
    }

    layout := HorizontalLayout {
        padding-left: 24px;
        padding-right: 24px;
        spacing: 20px;

        if (!icon-right && root.icon.width > 0 && root.icon.height > 0): Image {
            source <=> root.icon;
            width: 50px;
            //opacity: root.text-opacity;
            //colorize: root.colorize-icon ? root.text-color : transparent;
        }

        if (root.text != ""): Text {
            text: root.text;
            //color: root.text-color;
            //opacity: root.text-opacity;
            vertical-alignment: center;
            horizontal-alignment: center;
            //font-weight: MaterialFontSettings.label-large.font-weight;
            accessible-role: none;
            font-size: 60px;

            animate color {
                duration: 250ms;
                easing: ease;
            }
        }

        if (icon-right && root.icon.width > 0 && root.icon.height > 0): Image {
            source <=> root.icon;
            width: 50px;
            //opacity: root.text-opacity;
            //colorize: root.colorize-icon ? root.text-color : transparent;
        }
    }
}

export component NumericSetting {
    in property <string> unit: "°C";
    in property <image> icon <=> icon.source;
    in-out property <int> value: 93;

    preferred-width: 400px;
    height: 70px;

    HorizontalLayout {
        alignment: space-between;
        icon := Image {
            vertical-alignment: center;
            height: 75px;
            width: 70px;
            y: parent.height / 2 - self.height / 2;

            image-fit: ImageFit.contain;
        }

        Rectangle {
            width: 50px;
        }

        Image {
            source: @image-url("icons/numeric_arrow_left.svg");
            width: 28px;
            TouchArea {
                clicked => {
                    value = value - 1;
                }
            }
        }

        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            width: 300px;
            text: value + " " + unit;
            font-size: 40px;
        }

        Image {
            source: @image-url("icons/numeric_arrow_right.svg");
            width: 28px;
            TouchArea {
                clicked => {
                    value = value + 1;
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 480px;
    min-width: 800px;
    min-height: 480px;
    title: @tr("Coffee");

    /*
    Image {
        x: 0;
        y: 0;
        source: @image-url("UI_mock.png");
        width: parent.width;
        height: parent.height;
    }
*/
    Rectangle {
        y: 370px;
        border-color: black;
        border-width: 1px;
        height: 2px;
        width: 100%;
    }

    VerticalLayout {
        // Settings page
        Rectangle {
            height: 370px;
            width: 290px;

            Rectangle {
                height: 90%;
                width: 90%;
                border-color: black;
                border-width: 2px;
                //background: black.transparentize(80%);
                background: Colors.lightgray.transparentize(50%);

            VerticalLayout {
                //padding: 30px;
                alignment: center;
                spacing: 30px;
                Image {
                    x: parent.x + parent.width/2 - self.width/2;
                    source: @image-url("icons/gear.svg");
                    height: 200px;
                    width: 200px;
                    colorize: Colors.brown;
                }

                Text {
                    text: "Manual";
                    horizontal-alignment: center;
                    //horizontal-alignment: center;
                    font-size: 30px;
                }

            }
        }

            VerticalLayout {
                x: 310px;
                spacing: 40px;
                alignment: space-around;

                temperature := NumericSetting {
                    icon: @image-url("icons/thermometer.svg");
                }

                weight := NumericSetting {
                    icon: @image-url("icons/two_coffee_beans.svg");
                    unit: "g";
                    value: 15;
                }

                volume := NumericSetting {
                    icon: @image-url("icons/measurement_cup.svg");
                    unit: "ml";
                    value: 170;
                }
            }
        }

        // Back and Start menu
        HorizontalLayout {
            //height: 100px;
            width: 800px;
            alignment: space-between;
            padding: 10px;

            // Back button
            // Start Button
            back-btn := NavButton {
                text: "Back";
                icon: @image-url("icons/arrow_back.svg");
                height: 90px;
                width: 250px;

                clicked => {
                    temperature.value = 93;
                    weight.value = 15;
                    volume.value = 170;
                }
            }

            // Start Button
            start-btn := NavButton {
                text: "Start";
                icon: @image-url("icons/play_button.svg");
                height: 90px;
                width: 250px;
                icon-right: true;
            }
        }
    }

    //Text {text: "Hello World!";}
}
