

// Default button widget with Material Design Filled Button look and feel.
export component NavButton {
    in property <string> text: "Button";
    in property <image> icon;

    in property <bool> icon-right: false;

    callback clicked <=> ta.clicked;

    min-height: 10px;
    min-width: 200px;

    accessible-role: button;
    accessible-label: root.text;

    ta := TouchArea {
        x: 0;
        y: 0;
        height: root.height;
        width: root.width;
    }

    background := Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 20px;
        drop-shadow-color: transparent;
        drop-shadow-offset-y: 1px;
        background: Colors.lightgray;
        opacity: 0.4;
    }

    layout := HorizontalLayout {
        padding-left: 24px;
        padding-right: 24px;
        spacing: 20px;

        if (!icon-right && root.icon.width > 0 && root.icon.height > 0): Image {
            source <=> root.icon;
            width: 50px;
            //opacity: root.text-opacity;
            //colorize: root.colorize-icon ? root.text-color : transparent;
        }

        if (root.text != ""): Text {
            text: root.text;
            //color: root.text-color;
            //opacity: root.text-opacity;
            vertical-alignment: center;
            horizontal-alignment: center;
            //font-weight: MaterialFontSettings.label-large.font-weight;
            accessible-role: none;
            font-size: 60px;

            animate color {
                duration: 250ms;
                easing: ease;
            }
        }

        if (icon-right && root.icon.width > 0 && root.icon.height > 0): Image {
            source <=> root.icon;
            width: 50px;
            //opacity: root.text-opacity;
            //colorize: root.colorize-icon ? root.text-color : transparent;
        }
    }
}

export component NumericSetting {
    in property <string> unit: "°C";

    out property <int> value: 93;

    width: 300px;
    height: 70px;

    HorizontalLayout {
        alignment: center;
        Image {
            source: @image-url("icons/circle-check.svg");
            TouchArea {
                clicked => {
                    value = value - 1;
                }
                double-clicked => {
                    value = value - 1;
                }
            }
        }

        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            width: 200px;
            text: value + " " + unit;
            font-size: 40px;
        }

        Image {
            source: @image-url("icons/circle-check.svg");
            TouchArea {
                clicked => {
                    value = value + 1;
                }
                double-clicked => {
                    value = value + 1;
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 480px;
    min-width: 800px;
    min-height: 480px;
    title: @tr("Coffee");

    /*
    Image {
        x: 0;
        y: 0;
        source: @image-url("UI_mock.png");
        width: parent.width;
        height: parent.height;
    }
*/
    Rectangle {
        y: 370px;
        border-color: black;
        border-width: 1px;
        height: 2px;
        width: 100%;
    }

    VerticalLayout {
        // Settings page
        HorizontalLayout {
            height: 370px;

            VerticalLayout {
                spacing: 45px;
                NumericSetting { }
                NumericSetting { }
                NumericSetting { }
            }
        }

        // Back and Start menu
        HorizontalLayout {
            height: 110px;
            width: 800px;
            alignment: space-between;
            padding: 5px;

            // Back button
            // Start Button
            back-btn := NavButton {
                text: "Back";
                icon: @image-url("icons/arrow-right-long.svg");
                height: 100px;
                width: 250px;
            }

            // Start Button
            start-btn := NavButton {
                text: "Start";
                icon: @image-url("icons/arrow-right-long.svg");
                height: 100px;
                width: 250px;
                icon-right: true;
            }
        }
    }

    //Text {text: "Hello World!";}
}
