import { GlobalSettings } from "global_settings.slint";
import { ManualBrewScreen } from "pages/manual-brew.slint";
import { Page } from "pages/page.slint";
import { Selection } from "pages/selection.slint";



export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 480px;
    min-width: 800px;
    min-height: 480px;
    title: @tr("Coffee");

    if GlobalSettings.current-page == 0: Selection { }
    if GlobalSettings.current-page == 1: ManualBrewScreen { }
}
