export global GlobalSettings {
    in property <bool> widgets-enabled: true;
    out property <bool> animations: false;

    in property <int> current-page: 0;

    in property <float> balance: 110.23;

    in-out property <length> FontSizeLarge: 15pt;
    in-out property <length> FontSizeDefault: 12pt;

    out property <length> OverviewIconWidth: 40px;
    out property <length> layout-padding: 10px;
    out property <length> layout-spacing: 10px;

}
