export global Images {
    in property <image> arrow-left: @image-url("icons/arrow-left-long.svg");
    in property <image> arrow-right: @image-url("icons/arrow-right-long.svg");
    in property <image> check: @image-url("icons/circle-check.svg");
    in property <image> settings: @image-url("icons/gear.svg");
    in property <image> information: @image-url("icons/circle-info.svg");
    in property <image> dashboard: @image-url("icons/pen-to-square.svg");
    in property <image> coffee-beans: @image-url("icons/two_coffee_beans.svg");
    in property <image> cappuccino: @image-url("icons/cappuccino.svg");
    in property <image> latte: @image-url("icons/latte.svg");
    in property <image> americano: @image-url("icons/americano.svg");
    in property <image> espresso: @image-url("icons/espresso.svg");
}